CREATE TABLE IF NOT EXISTS public.result_data
(
    id uuid NOT NULL,
    id_indata uuid NOT NULL,
    date_created date NOT NULL,
    date_updated date,
    user_created uuid NOT NULL,
    user_updated uuid,
    transaction_id uuid NOT NULL,
    transaction_status_new character varying(8) COLLATE pg_catalog."default" NOT NULL,
    transaction_amount numeric NOT NULL,
    transaction_currency character(3) COLLATE pg_catalog."default" NOT NULL,
    transaction_description character varying(200) COLLATE pg_catalog."default",
    version smallint NOT NULL,
    CONSTRAINT result_data_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.sync_log
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 10 ),
    date_sync timestamp with time zone NOT NULL,
    result character varying(2000) COLLATE pg_catalog."default",
    CONSTRAINT sync_log_pkey PRIMARY KEY (id)
)